name: mla23dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - sphinx
  - jupyter-book
  - pip
  - pip:
    - pyyaml
    - numpy
    - scipy
    - pandas
    - matplotlib
    - scikit-learn
    - scikit-optimize
    - jax
    - jaxlib
    - ghp-import
    - seaborn
    - ipywidgets
    - jupyter

